export default {
    
   USER_FETCH_PROFILE_START: 'USER_FETCH_PROFILE_START',
   USER_FETCH_PROFILE_SUCCESS: 'USER_FETCH_PROFILE_SUCCESS',
   USER_FETCH_PROFILE_ERROR: 'USER_FETCH_PROFILE_ERROR',

   USER_UPDATE_PROFILE_START: 'USER_UPDATE_PROFILE_START',
   USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
   USER_UPDATE_PROFILE_ERROR: 'USER_UPDATE_PROFILE_ERROR',

   CLEAR_UPDATE_USER_PROFILE: 'CLEAR_UPDATE_USER_PROFILE',

   FETCH_SHIPPED_PRODUCTS_START: 'FETCH_SHIPPED_PRODUCTS_START',
   FETCH_SHIPPED_PRODUCTS_SUCCESS: 'FETCH_SHIPPED_PRODUCTS_SUCCESS',
   FETCH_SHIPPED_PRODUCTS_ERRORED: 'FETCH_SHIPPED_PRODUCTS_ERRORED',

   FETCH_STOCK_PRODUCTS_START: 'FETCH_STOCK_PRODUCTS_START',
   FETCH_STOCK_PRODUCTS_SUCCESS: 'FETCH_STOCK_PRODUCTS_SUCCESS',
   FETCH_STOCK_PRODUCTS_ERRORED: 'FETCH_STOCK_PRODUCTS_ERRORED',

   FETCH_SALES_PRODUCTS_START: 'FETCH_SALES_PRODUCTS_START',
   FETCH_SALES_PRODUCTS_SUCCESS: 'FETCH_SALES_PRODUCTS_SUCCESS',
   FETCH_SALES_PRODUCTS_ERRORED: 'FETCH_SALES_PRODUCTS_ERRORED',
   
} 