export default {
    
   USER_FETCH_PROFILE_START: 'USER_FETCH_PROFILE_START',
   USER_FETCH_PROFILE_SUCCESS: 'USER_FETCH_PROFILE_SUCCESS',
   USER_FETCH_PROFILE_ERROR: 'USER_FETCH_PROFILE_ERROR',

   USER_UPDATE_PROFILE_START: 'USER_UPDATE_PROFILE_START',
   USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
   USER_UPDATE_PROFILE_ERROR: 'USER_UPDATE_PROFILE_ERROR',

   CLEAR_UPDATE_USER_PROFILE: 'CLEAR_UPDATE_USER_PROFILE',
} 