export default {
    
   USER_FETCH_PROFILE_START: 'USER_FETCH_PROFILE_START',
   USER_FETCH_PROFILE_SUCCESS: 'USER_FETCH_PROFILE_SUCCESS',
   USER_FETCH_PROFILE_ERROR: 'USER_FETCH_PROFILE_ERROR',

   USER_UPDATE_PROFILE_START: 'USER_UPDATE_PROFILE_START',
   USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
   USER_UPDATE_PROFILE_ERROR: 'USER_UPDATE_PROFILE_ERROR',

   CLEAR_UPDATE_USER_PROFILE: 'CLEAR_UPDATE_USER_PROFILE',

   FETCH_SHIPPED_PRODUCTS_START: 'FETCH_SHIPPED_PRODUCTS_START',
   FETCH_SHIPPED_PRODUCTS_SUCCESS: 'FETCH_SHIPPED_PRODUCTS_SUCCESS',
   FETCH_SHIPPED_PRODUCTS_ERRORED: 'FETCH_SHIPPED_PRODUCTS_ERRORED',

   FETCH_STOCK_PRODUCTS_START: 'FETCH_STOCK_PRODUCTS_START',
   FETCH_STOCK_PRODUCTS_SUCCESS: 'FETCH_STOCK_PRODUCTS_SUCCESS',
   FETCH_STOCK_PRODUCTS_ERRORED: 'FETCH_STOCK_PRODUCTS_ERRORED',

   FETCH_SALES_PRODUCTS_START: 'FETCH_SALES_PRODUCTS_START',
   FETCH_SALES_PRODUCTS_SUCCESS: 'FETCH_SALES_PRODUCTS_SUCCESS',
   FETCH_SALES_PRODUCTS_ERRORED: 'FETCH_SALES_PRODUCTS_ERRORED',

   FETCH_INSIGHTS_START: 'FETCH_INSIGHTS_START',
   FETCH_INSIGHTS_SUCCESS: 'FETCH_INSIGHTS_SUCCESS',
   FETCH_INSIGHTS_ERRORED: 'FETCH_INSIGHTS_ERRORED',

   FETCH_DAILY_SALES_START: 'FETCH_DAILY_SALES_START',
   FETCH_DAILY_SALES_SUCCESS: 'FETCH_DAILY_SALES_SUCCESS',
   FETCH_DAILY_SALES_ERRORED: 'FETCH_DAILY_SALES_ERRORED',

   FETCH_EMAIL_SUBS_START: 'FETCH_EMAIL_SUBS_START',
   FETCH_EMAIL_SUBS_SUCCESS: 'FETCH_EMAIL_SUBS_SUCCESS',
   FETCH_EMAIL_SUBS_ERRORED: 'FETCH_EMAIL_SUBS_ERRORED',

   FETCH_COMPLETED_TASKS_START: 'FETCH_COMPLETED_TASKS_START',
   FETCH_COMPLETED_TASKS_SUCCESS: 'FETCH_COMPLETED_TASKS_SUCCESS',
   FETCH_COMPLETED_TASKS_ERRORED: 'FETCH_COMPLETED_TASKS_ERRORED',

   FETCH_TASKS_START: 'FETCH_TASKS_START',
   FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
   FETCH_TASKS_ERRORED: 'FETCH_TASKS_ERRORED',

   FETCH_EMPLOYEE_STATS_START: 'FETCH_EMPLOYEE_STATS_START',
   FETCH_EMPLOYEE_STATS_SUCCESS: 'FETCH_EMPLOYEE_STATS_SUCCESS',
   FETCH_EMPLOYEE_STATS_ERRORED: 'FETCH_EMPLOYEE_STATS_ERRORED',
   
} 